version: '3.4'

services:
  schoolapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "44389:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  studentadmissionmanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"


  studentattendancemanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

